### ISSUE TITLE
手机端支付无法调起支付宝 App

### ISSUE THREAD

**Issue by yarin-zhang** [iwillhappy1314/wenprise-alipay-checkout-for-woocommerce#10]
您好，我安装插件并配置完毕后，电脑端已经可以正常支付了。

但是在手机端上却无法正常付款，不会跳转。直接显示”处理结算时出错，请重试“，然后不断重新加载网页。

支付宝账号已经开通了”手机网站支付“权限。能否帮忙检查一下原因？

**Comment by yarin-zhang** [comment]
我找到了原因，是 iOS 的 设置 - Safari 中有一个“阻止弹出式窗口”的选项，关闭这个选项就可以自动跳转界面了……这个问题可以解决一下吗？比如换成当前网页调起支付服务？因为很多用户这个选项是默认开启的。

**Comment by iwillhappy1314** [comment]
反馈已收到，下个版本中考虑增加此功能。
