### ISSUE TITLE
手机端支付时出现The biz_content product_code parameter is required错误

### ISSUE THREAD

**Issue by clicoc** [iwillhappy1314/wenprise-alipay-checkout-for-woocommerce#12]
接入的当面付，手机端支付时出现The biz_content product_code parameter is required错误，这是什么错误？

**Comment by NicoChiGu** [comment]
试试class-checkout.php 430行  `$order_data = apply_filters('woocommerce_wenprise_alipay_args',[ ... ]`     传入
`product_code` 值为 `FACE_TO_FACE_PAYMENT`

还有362行 `if (wp_is_mobile()) { $gateway = Omnipay::create('Alipay_AopWap');`  改为 `Alipay_AopF2F'` 可以正常拿到支付码了
![image](https://github.com/iwillhappy1314/wenprise-alipay-checkout-for-woocommerce/assets/34607782/0220e322-af72-4f21-8d60-0803b856b568)

**Comment by NicoChiGu** [comment]
唤醒支付宝支付直接访问二维码生产的$code_url 页面也能实现 参照wap的button改一下href用的是$code_url就可以

                    <div class="rs-flex rs-justify-center rs-mt-4 rs-action-block">
                        <a target="_blank" class="button alt rs-flex rs-payment-url rswc-button" href="<?= $code_url; ?>">
                            <svg t="1682581409962" class="icon" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg" p-id="2628" width="24" height="24"><path d="M789 610.3c-38.7-12.9-90.7-32.7-148.5-53.6 34.8-60.3 62.5-129 80.7-203.6H530.5v-68.6h233.6v-38.3H530.5V132h-95.4c-16.7 0-16.7 16.5-16.7 16.5v97.8H182.2v38.3h236.3v68.6H223.4v38.3h378.4a667.18 667.18 0 0 1-54.5 132.9c-122.8-40.4-253.8-73.2-336.1-53-52.6 13-86.5 36.1-106.5 60.3-91.4 111-25.9 279.6 167.2 279.6C386 811.2 496 747.6 581.2 643 708.3 704 960 808.7 960 808.7V659.4s-31.6-2.5-171-49.1zM253.9 746.6c-150.5 0-195-118.3-120.6-183.1 24.8-21.9 70.2-32.6 94.4-35 89.4-8.8 172.2 25.2 269.9 72.8-68.8 89.5-156.3 145.3-243.7 145.3z" p-id="2629" fill="#ffffff"></path></svg>
                            支付宝支付
                        </a>
                        <a href="#" id="js-alipay-fail" class="button rswc-button rs-flex alt2 rs-ml-4">
                            <?= __('查询支付结果', 'wprs-wc-alipay'); ?>
                        </a>
                    </div>

**Comment by clicoc** [comment]
谢谢，解决了
