### ISSUE TITLE
如何让这个插件支持woocommerce subscription的Multiple Subscriptions功能？

### ISSUE THREAD

**Issue by zx900930** [iwillhappy1314/wenprise-alipay-checkout-for-woocommerce#4]
官方的说明：
https://docs.woocommerce.com/document/subscriptions/payment-gateways/#section-3
文档：
https://docs.woocommerce.com/document/subscriptions/multiple-subscriptions/

或者支持自动续期(Auto Renewal)也行
https://docs.woocommerce.com/document/subscriptions/renewal-process/

**Comment by iwillhappy1314** [comment]
这个功能需要支付宝「周期扣款」服务，考虑到此服务的申请门槛比较高，用到的机会应该比较少，暂时没有计算支持此功能。
