### ISSUE TITLE
php7.2  启用后报错

### ISSUE THREAD

**Issue by qq492269704** [iwillhappy1314/wenprise-alipay-checkout-for-woocommerce#6]
Warning: require(/www/wwwroot/www.demo.com/wp-content/plugins/wenprise-alipay-checkout-for-woocommerce-master/vendor/composer/../symfony/polyfill-php70/bootstrap.php): failed to open stream: No such file or directory in /www/wwwroot/www.demo.com/wp-content/plugins/wenprise-alipay-checkout-for-woocommerce-master/vendor/composer/autoload_real.php on line 69

Fatal error: require(): Failed opening required '/www/wwwroot/www.demo.com/wp-content/plugins/wenprise-alipay-checkout-for-woocommerce-master/vendor/composer/../symfony/polyfill-php70/bootstrap.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/www.demo.com/wp-content/plugins/wenprise-alipay-checkout-for-woocommerce-master/vendor/composer/autoload_real.php on line 69

**Comment by iwillhappy1314** [comment]
开发版本没有经过严格测试，不建议使用，请从WordPress后台插件安装页面直接搜索「wenprise alipay」安装。
